// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANalmRzCFPawgfKxzVfeqIPbfyNgjGF_M',
    appId: '1:763894004214:web:1050e7e73fcb254c22afd7',
    messagingSenderId: '763894004214',
    projectId: 'fir-learn-93ccc',
    authDomain: 'fir-learn-93ccc.firebaseapp.com',
    storageBucket: 'fir-learn-93ccc.appspot.com',
    measurementId: 'G-GEED8TH9R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmkQqB2I-mDP-dmn4o377JA2A4Uu22zP8',
    appId: '1:763894004214:android:a024cfe18e85d26d22afd7',
    messagingSenderId: '763894004214',
    projectId: 'fir-learn-93ccc',
    storageBucket: 'fir-learn-93ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HnVRZhweL5LbnOgfAWeQvQMjYMJVPPQ',
    appId: '1:763894004214:ios:da3a6c5094701e0822afd7',
    messagingSenderId: '763894004214',
    projectId: 'fir-learn-93ccc',
    storageBucket: 'fir-learn-93ccc.appspot.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HnVRZhweL5LbnOgfAWeQvQMjYMJVPPQ',
    appId: '1:763894004214:ios:08c34cd145cb7ad722afd7',
    messagingSenderId: '763894004214',
    projectId: 'fir-learn-93ccc',
    storageBucket: 'fir-learn-93ccc.appspot.com',
    iosBundleId: 'com.example.flutterLearn.RunnerTests',
  );
}
